spring:
  application:
    name: kotlin-api
  profiles:
    default: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    validate-on-migrate: true
  session:
    data:
      redis:
        namespace: kotlin-api:session
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.realm-url}
          audiences:
            - kotlin-api
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api/v1
    session:
      timeout: 10h
      cookie:
        name: KOTLIN_API_SESSION
        http-only: true
        secure: true
        same-site: lax

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

application:
  keycloak:
    client-id: kotlin-api
