spring:
  devtools:
    restart:
      additional-paths: src/main/kotlin,src/main/resources
      poll-interval: 2s
      quiet-period: 1s
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin_api
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025

server:
  servlet:
    session:
      cookie:
        secure: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

application:
  mail:
    from: no-reply@kotlin-api.local
  frontend:
    url: http://localhost:8080
  keycloak:
    realm-url: http://localhost:9000/realms/kotlin-api
    client-secret: kotlin-api-local-secret
  auth:
    callback-url: http://localhost:8080/api/v1/auth/callback
    post-login-url: http://localhost:8080/api/v1/swagger-ui.html

logging:
  level:
    com.vertyll.kotlinapi: DEBUG
